#!/usr/bin/env bash

# Install the latest PostgreSQL from PGDG repo and configure it for ZFS

set -e

apt-get update -q
apt-get install -yq --no-install-recommends postgresql-common

/usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y

apt-get install -yq postgresql

pg_version=$(ls /etc/postgresql | sort -n | tail -1)

cat > "/etc/postgresql/${pg_version}/main/conf.d/zfs.conf" <<EOF
full_page_writes=off
synchronous_commit=off
wal_init_zero=off
wal_recycle=off
EOF

systemctl restart postgresql

